using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

/**
 * auto generated by KeyMapper
 */
[CreateAssetMenu(menuName = "ScriptableObject/KeyMapper")]
public class KeyMapper : ScriptableObject
{
    public string[] keyName;
    public string[] value;

    public static KeyMapper Create()
    {
        return ScriptableObject.CreateInstance<KeyMapper>();
    }

    public static KeyMapper Load(string key)
    {
        return Resources.Load<KeyMapper>("KeyMapper/" + key);
    }

    public static KeyMapper Instantiate(string key)
    {
        return UnityEngine.Object.Instantiate<KeyMapper>(Load(key));
    }

    public string this[string name]
    {
        get
        {
            int index = Array.IndexOf(keyName, name);

            if (index == -1)
            {
                return null;
            }

            return value[index];
        }
    }
}
