using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

/**
 * auto generated by PurgeKeys
 */
[CreateAssetMenu(menuName="ScriptableObject/PurgeKeys")]
public class PurgeKeys : ScriptableObject
{
    public string[] displayNames;
    public string[] names;
    public string[] ids;

    public static PurgeKeys Create()
    {
        return ScriptableObject.CreateInstance<PurgeKeys>();
    }

    public static PurgeKeys Load(string key)
    {
        return Resources.Load<PurgeKeys>("PurgeKeys/" + key);
    }

    public static PurgeKeys Instantiate(string key)
    {
        return Object.Instantiate<PurgeKeys>(Load(key));
    }
}
